[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy_dylib = "0.15"
bevy-inspector-egui = "0.29"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3